image:
  file: .gitpod.dockerfile

tasks:
  - name: go-dependencies
    init: go get -v -t -d ./...
  - name: tools
    init: | 
      npm install
      curl https://get.wasmer.io -sSfL | sh
      source /home/gitpod/.wasmer/wasmer.sh
      
ports:
  - port: 8080
    visibility: public
    
vscode:
  extensions:
    - golang.go
    - wayou.vscode-todo-highlight
    - coenraads.bracket-pair-colorizer-2
