image:
  file: .gitpod.dockerfile

tasks:
  - name: select-go-116
    init: |
      gvm use go1.16
      npm install
      clear
    
ports:
  - port: 8080
    visibility: public

vscode:
  extensions:
    - golang.go
    - wayou.vscode-todo-highlight
    - coenraads.bracket-pair-colorizer-2
