image:
  file: .gitpod.dockerfile

tasks:
  - name: go-install
    init: |
      echo "👋 installing go"
      #bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
      #source /home/gitpod/.gvm/scripts/gvm
      #gvm install go1.13 -B
      #gvm use go1.13
      echo "👋 go dependencies"
      go get -v -t -d ./...

      echo "👋 installing tinygo"
      wget https://github.com/tinygo-org/tinygo/releases/download/v0.18.0/tinygo_0.18.0_amd64.deb
      sudo dpkg -i tinygo_0.18.0_amd64.deb
      rm tinygo_0.18.0_amd64.deb
      export PATH=$PATH:/usr/local/tinygo/bin
      tinygo version 

      echo "👋 installing wasmer"
      curl https://get.wasmer.io -sSfL | sh
      source /home/gitpod/.wasmer/wasmer.sh
    
ports:
  - port: 8080
    visibility: public

vscode:
  extensions:
    - golang.go
    - wayou.vscode-todo-highlight
    - coenraads.bracket-pair-colorizer-2
