image:
  file: .gitpod.dockerfile

tasks:
  - name: go-install
    init: |
      gvm use go1.16
      go version
      tinygo version
      curl https://get.wasmer.io -sSfL | sh
      source /home/gitpod/.wasmer/wasmer.sh    
    
ports:
  - port: 8080
    visibility: public

vscode:
  extensions:
    - golang.go
    - wayou.vscode-todo-highlight
    - coenraads.bracket-pair-colorizer-2
